name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # GitHub veb-saytida "Run workflow" tugmasi orqali qo'lda ishga tushirish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kodni yuklab olish
        uses: actions/checkout@v4

      - name: Java 17 o'rnatish
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle o'rnatish va sozlash
        uses: gradle/actions/setup-gradle@v3

      - name: APK ni Build qilish (Gradle)
        run: |
          gradle assembleDebug --stacktrace

      - name: Tayyor APK faylini saqlash (Upload Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: FPS-Booster-App-Debug
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 14
